### PR TITLE
Better dedup tests

### PR DESCRIPTION
**Pull request by danamansana**
We had a problem in the past with our deduplication method only catching duplicates that occur in different event batches. That is now fixed, but the tests were not updated. This branch updates the tests to specifically check for duplicates in the same batch and in different batches, in order to prevent future rewrites from tripping on one of these cases

### CODE REVIEW

**Comment by ktp242** [comment]
Looks good. So basically, if we run into a duplicate data, no matter which batch it is from, we will not process it again, unless `ENV['CHECKOUT_ID_EXPIRE_TIME'] = nil` which means this data could be considered not a duplicate.

How much time is 'CHECKOUT_ID_EXPIRE_TIME' for now?

**Comment by danamansana** [comment]
Yikes! Good catch. It looks like the CHECKOUT_ID_EXPIRE_TIME is not configured in production. It is set to 3600 in the local sam file, so we should probably set it to the same in production, at least for now

**Comment by ktp242** [comment]
Does it mean on Prod we are actually processing duplicates data currently?

**Comment by danamansana** [comment]
Yes, it looks like that should be the case.
I've just added a new PR to make sure this gets set in travis

**Review by ktp242 — APPROVED** [review]

**Pull request merged**
